### ISSUE TITLE
skip_breaths_without_be

### ISSUE THREAD

**Issue by Piffo** [hahnicity/ventMAP#3]
Hi @hahnicity,
I'm working with a csv file that has BS but not BE label.

I tried to set the flag "skip_breaths_without_be" at True (how reported
in 'Readme.md' ( _create generator that will iterate through file. Specify False to ensure that
breaths without BS/BE markers will be dropped. If you say True, then breaths
 without BS/BE will be kept_) , but seems that the ventMAP 
library skip anyway the breath without BE. 
It seems to be an issue: in fact, when the flow/pressure sequence reach the end, the
case
`elif row[self.bs_col].strip() == "BE":` (line 164 of raw_utilis.py)
is not called, and so the append to data_list doesn't happen.

Here there's the file that I'm trying to parse.

[test_breath.zip](https://github.com/hahnicity/ventMAP/files/5542002/test_breath.zip)

Michele

**Comment by hahnicity** [comment]
Hi @Piffo , lemme look into this.

**Comment by hahnicity** [comment]
This issue has been resolved in `ventmap==1.4.7` if you want to install do `pip install -U ventmap`.

Please close this issue if it has been resolved to your satisfaction
